<a href="https://colab.research.google.com/github/devthumos/Processamento_de_Linguagem_Natural/blob/main/Atividade_Avaliativa__04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade Avaliativa 04 - Implementação de uma multilayer perceptron para resolução do problema XOR

In [ ]:
import numpy as np
import pandas as pd
import math
import random

In [ ]:
# É O CORRETO

final_output = 0
output_12_zipped = 0
output_1 = 0
output_2 = 0
w1_12, w1_34, w2 = 0, 0, 0

def perceptron(w, b, X, Y="NaN"):
  z = np.dot(X, w.T)
  a = 1 / (1 + np.exp(-z))
  return a

def backward(X, Y, lr, epochs):
  global final_output, output_12_zipped, output_1, output_2, w1_12, w1_34, w2
  w1_12, w1_34, w2 = w1_12.T, w1_34.T, w2.T
  # print("\t\tANTES\n", w1_12, w1_34, w2)

  y_hats = final_output
  dw2 = np.array([0, 0])

  for i in range(epochs):
    for y_hat, y, output_12 in zip(y_hats, Y, output_12_zipped):
      ##### Para o dw2, esse é o correto? PERGUNTAR PARA O PROFESSOR
      ## COMO QUE EU FAÇO AQUI QUANDO O Y É 0, EU NORMALIZO ANTES?
      dw2 = (1 - y) * (y - y_hat)  * y 
      print(dw2)  ##TESTE
      return 0  ##TESTE
      w2[0] = w2[0] - lr * dw2
      w2[1] = w2[1] - lr * dw2

      #### $$$$  BACKWARD DO PERCEPTRON 1 E DO PERCEPTRON 2  $$$$ ####
      dw1_12 = output_12[0]  * (1 - output_12[0]) * dw2
      dw1_34 = output_12[1] * (1 - output_12[1]) * dw2
      w1_12[0] = w1_12[0] - lr * dw1_12
      w1_12[1] = w1_12[1] - lr * dw1_12
      w1_34[0] = w1_34[0] - lr * dw1_34
      w1_34[1] = w1_34[1] - lr * dw1_34

  # print("\t\tDEPOIS\n", w1_12, w1_34, w2)
  w1_12, w1_34, w2 = w1_12.T, w1_34.T, w2.T

  return w1_12, w1_34, w2


def forward(X, Y="Nan", weights=False):
  global final_output, output_12_zipped, output_1, output_2, w1_12, w1_34, w2

  if not weights:
    w1_12 = np.zeros((1, X.shape[1]))
    w1_34 = np.zeros((1, X.shape[1]))
    w2 = np.zeros((1, X.shape[1]))
  else:
    pass

  b1_12 = 0
  b1_34 = 0
  b2 = 0

  output_1 = perceptron(w1_12, b1_12, X)
  output_2 = perceptron(w1_34, b1_34, X)

  output_12_zipped = np.stack((output_1, output_2), axis=-1)
  output_12_zipped = np.squeeze(output_12_zipped)

  final_output = perceptron(w2, b2, output_12_zipped, Y)

  return final_output

In [ ]:
X = np.array([
     [0, 0],
     [0, 1],
     [1, 0],
     [1, 1],
])
Y = np.array([0, 1, 1, 0])

In [ ]:
np.random.seed(10)

w1_12 = np.random.randn(1, X.shape[1])
b1_12 = 0

w1_34 = np.random.randn(1, X.shape[1])
b1_34 = 0

w2 = np.random.randn(1, X.shape[1])
b2 = 0

print(w1_12, w1_34, w2, sep="\n\n")

[[1.3315865  0.71527897]]

[[-1.54540029 -0.00838385]]

[[ 0.62133597 -0.72008556]]


In [ ]:
forward(X, Y, weights=True)

array([[0.48765881],
       [0.51467952],
       [0.59024651],
       [0.60458109]])

In [ ]:
print(w1_12, w1_34, w2, sep="\n\n")

[[1.3315865  0.71527897]]

[[-1.54540029 -0.00838385]]

[[ 0.62133597 -0.72008556]]


In [ ]:
backward(X, Y, 0.15, 1)

[-0.]


0

In [ ]:
print(w1_12, w1_34, w2, sep="\n\n")

[[1.3315865  0.71527897]]

[[-1.54540029 -0.00838385]]

[[ 0.62133597 -0.72008556]]


In [ ]:
print(forward(np.array([[0, 0]]), weights=True))
print(forward(np.array([[0, 1]]), weights=True))
print(forward(np.array([[1, 0]]), weights=True))
print(forward(np.array([[1, 1]]), weights=True))

[0.48765881]
[0.51467952]
[0.59024651]
[0.60458109]
